//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestUtilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestUtilities.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProtobufMapping&gt;
        ///  &lt;MappedElement&gt;
        ///    &lt;Name&gt;NumericRepresentation&lt;/Name&gt;
        ///    &lt;Id&gt;108&lt;/Id&gt;
        ///  &lt;/MappedElement&gt;
        ///  &lt;MappedElement&gt;
        ///    &lt;Name&gt;NumericRepresentation1&lt;/Name&gt;
        ///    &lt;Id&gt;109&lt;/Id&gt;
        ///  &lt;/MappedElement&gt;
        ///  &lt;MappedElement&gt;
        ///    &lt;Name&gt;NumericRepresentation2&lt;/Name&gt;
        ///    &lt;Id&gt;110&lt;/Id&gt;
        ///  &lt;/MappedElement&gt;
        ///  &lt;MappedElement&gt;
        ///    &lt;Name&gt;NumericRepresentation3&lt;/Name&gt;
        ///    &lt;Id&gt;111&lt;/Id&gt;
        ///  &lt;/MappedElement&gt;
        ///  &lt;MappedElement&gt;
        ///    &lt;Name&gt;NumericRepresentation4&lt;/Name&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProtobufMappingTest {
            get {
                return ResourceManager.GetString("ProtobufMappingTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProtobufMapping&gt;
        ///  &lt;MappedElement&gt;
        ///    &lt;Name&gt;TestUtilities.ProtobufContract.ProtobufContractGenerator._mapper&lt;/Name&gt;
        ///    &lt;Id&gt;1&lt;/Id&gt;
        ///  &lt;/MappedElement&gt;
        ///  &lt;MappedElement&gt;
        ///    &lt;Name&gt;TestUtilities.ProtobufContract.ProtobufContractGenerator._model&lt;/Name&gt;
        ///    &lt;Id&gt;2&lt;/Id&gt;
        ///  &lt;/MappedElement&gt;
        ///  &lt;MappedElement&gt;
        ///    &lt;Name&gt;TestUtilities.ProtobufContract.TestClassA.AString1&lt;/Name&gt;
        ///    &lt;Id&gt;3&lt;/Id&gt;
        ///  &lt;/MappedElement&gt;
        ///  &lt;MappedElement&gt;
        ///    &lt;Name&gt;TestUtilities.ProtobufCon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProtobufMappingTest2 {
            get {
                return ResourceManager.GetString("ProtobufMappingTest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProtobufMapping&gt;
        ///  &lt;MappedElement&gt;
        ///    &lt;Name&gt;TestUtilities.ProtobufContract.ProtobufContractGenerator._mapper&lt;/Name&gt;
        ///    &lt;Id&gt;1&lt;/Id&gt;
        ///  &lt;/MappedElement&gt;
        ///  &lt;MappedElement&gt;
        ///    &lt;Name&gt;TestUtilities.ProtobufContract.ProtobufContractGenerator._model&lt;/Name&gt;
        ///    &lt;Id&gt;2&lt;/Id&gt;
        ///  &lt;/MappedElement&gt;
        ///  &lt;MappedElement&gt;
        ///    &lt;Name&gt;TestUtilities.ProtobufContract.TestClassA.AString1&lt;/Name&gt;
        ///    &lt;Id&gt;10&lt;/Id&gt;
        ///  &lt;/MappedElement&gt;
        ///  &lt;MappedElement&gt;
        ///    &lt;Name&gt;TestUtilities.ProtobufCo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProtobufMappingTest3 {
            get {
                return ResourceManager.GetString("ProtobufMappingTest3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] test {
            get {
                object obj = ResourceManager.GetObject("test", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
