name: CI

on: 
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK '5.0'
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Plugin Test
        run: dotnet test ./PluginTest/PluginTest.csproj -c Release
      - name: Acceptance Test
        run: dotnet test ./AcceptanceTest/AcceptanceTest.csproj -c Release